import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATABASE_PATH = BASE_DIR / "examguard.db"
UPLOAD_FOLDER = BASE_DIR / "uploads"
PHOTOS_FOLDER = UPLOAD_FOLDER / "photos"
EVIDENCE_FOLDER = UPLOAD_FOLDER / "evidence"
PHOTOS_FOLDER.mkdir(parents=True, exist_ok=True)
EVIDENCE_FOLDER.mkdir(parents=True, exist_ok=True)

# Explicit, configurable monitoring thresholds
FACE_ABSENT_THRESHOLD = 10
TAB_SWITCH_THRESHOLD = 3
FOCUS_LOSS_THRESHOLD = 3
MULTIPLE_FACES_THRESHOLD = 1

# Explicit integrity weights (risk points)
WEIGHT_FACE_ABSENCE = 10
WEIGHT_MULTIPLE_FACES = 30
WEIGHT_TAB_SWITCH = 10
WEIGHT_FOCUS_LOSS = 5
WEIGHT_FULLSCREEN_EXIT = 10

LOW_RISK_MIN = 80.0
MEDIUM_RISK_MIN = 50.0

class Config:
    SECRET_KEY = os.environ.get("SECRET_KEY", "examguard-super-secret-production-key-2026")
    SQLALCHEMY_DATABASE_URI = os.environ.get("DATABASE_URL", f"sqlite:///{DATABASE_PATH.as_posix()}")
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    MAX_CONTENT_LENGTH = 16 * 1024 * 1024
    UPLOAD_FOLDER = str(UPLOAD_FOLDER)
    PHOTOS_FOLDER = str(PHOTOS_FOLDER)
    EVIDENCE_FOLDER = str(EVIDENCE_FOLDER)
    ALLOWED_EXTENSIONS = {"png", "jpg", "jpeg", "webp"}

    FACE_ABSENT_THRESHOLD = FACE_ABSENT_THRESHOLD
    TAB_SWITCH_THRESHOLD = TAB_SWITCH_THRESHOLD
    FOCUS_LOSS_THRESHOLD = FOCUS_LOSS_THRESHOLD
    MULTIPLE_FACES_THRESHOLD = MULTIPLE_FACES_THRESHOLD
    WEIGHT_FACE_ABSENCE = WEIGHT_FACE_ABSENCE
    WEIGHT_MULTIPLE_FACES = WEIGHT_MULTIPLE_FACES
    WEIGHT_TAB_SWITCH = WEIGHT_TAB_SWITCH
    WEIGHT_FOCUS_LOSS = WEIGHT_FOCUS_LOSS
    WEIGHT_FULLSCREEN_EXIT = WEIGHT_FULLSCREEN_EXIT
    LOW_RISK_MIN = LOW_RISK_MIN
    MEDIUM_RISK_MIN = MEDIUM_RISK_MIN
